version: 0.2

phases:
    install:
      commands:
        - echo Installing dependencies
        - yum update  -y
        - nano /etc/yum.repos.d/mongodb-org-4.4.repo
        - yum install -y mongodb-org
        - yum -y install nodejs
        - npm install
    pre_build:
      commands:
        - echo Starting mongodb
        - sudo systemctl start mongod
        - sudo systemctl enable mongod

      
