version: 0.2

phases:
    install:
      commands:
        - echo Installing dependencies
        - sudo yum install -y mongodb-org
        - yum -y install nodejs
        - npm install
    pre_build:
      commands:
        - echo Starting mongodb
        - sudo systemctl start mongod
        - sudo systemctl enable mongod

      
