version: 0.2

phases:
    install:
      commands:
        - echo Installing dependencies
        - apt update
        - apt install nodejs npm
        - apt install mongodb
    pre_build:
      commands:
        - echo Starting mongodb
        - systemctl start mongod
        - systemctl enable mongod

      
