version: 0.2

phases:
    install:
      commands:
        - echo Installing dependencies
        - sudo apt update
        - sudo apt install nodejs npm
        - sudo apt install mongodb
    pre_build:
      commands:
        - echo Starting mongodb
        - systemctl start mongod
        - systemctl enable mongod

      
